apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-coworking
  name: backend-coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend-coworking
  template:
    metadata:
      labels:
        service: backend-coworking
    spec:
      containers:
        - image: 012291751200.dkr.ecr.us-west-2.amazonaws.com/udacity-prj3-ecr:latest
          name: backend-coworking
          imagePullPolicy: Always
          ports:
            - containerPort: 5153
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /readiness_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              memory: "1000Mi"
              cpu: "250m"
            limits:
              memory: "2000Mi"
              cpu: "500m"
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: env-config
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-coworking
  name: backend-coworking
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 5153
      targetPort: 5153
  selector:
    service: backend-coworking